### ISSUE TITLE
这个压缩包使用该程序操作后转化的PDF只有前11页就结束了

### ISSUE THREAD

**Issue by yeyanfeng** [Davy-Zhou/zip2pdf#6]
秒传码：bbef034af3a3bcd5a2063bf5cc2b9062#146427238#中国近代史通鉴  1840-1949  抗日战争,孙景峰,北京：红旗出版社_10166735.zip

**Comment by Davy-Zhou** [comment]
> 秒传码：bbef034af3a3bcd5a2063bf5cc2b9062#146427238#中国近代史通鉴 1840-1949 抗日战争,孙景峰,北京：红旗出版社_10166735.zip

经过测试，我这里是正常的，最后的结果是1000多页，**发一下转换过程的录屏，相关隐私信息注意打码**

**Comment by yeyanfeng** [comment]
> 经过测试，我这里是正常的，最后的结果是1000多页，**发一下转换过程的录屏，相关隐私信息注意打码**

感谢解答，我又去操作了一遍，结果是正常的。
我发现是我自己操作不当造成的，当解压完弹出Pdg2Pic转换的时候，会弹出一个小对话框我以为是我要手动点是，导致程序出错，刚才最后一遍的时候我撒手不管，程序全自动完成了，结果是好的。
怪我自己没有自己看操作说明，抱歉添麻烦了。
